[settings]
dsn=project
tableprefix=pt_
mapping=/project
rootURL=http://www.yoursite.com
adminEmail=admin@localhost
guestUserAutoLogin=0
allowRegister=0
mailServer=
mailUsername=
mailPassword=
version=2.3.4