[settings]
dsn=project
dbtype=mssql
tableprefix=pt_
mapping=/project
rootURL=http://127.0.0.1
adminEmail=admin@localhost
guestUserAutoLogin=0
allowRegister=0
mailServer=
mailUsername=
mailPassword=
showDebug=true
errorPage=false
showError=true
version=2.4.4