[settings]
dsn=project
tableprefix=pt_
mapping=/project
rootURL=http://www.yoursite.com
adminEmail=admin@localhost
guestUserAutoLogin=0
allowRegister=0
mailServer=
mailUsername=
mailPassword=
showDebug=false
errorPage=true
showError=false
version=2.4.5